//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JPLoto.Globalization.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AuthResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AuthResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JPLoto.Shared.Resources.AuthResource", typeof(AuthResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ユーザーログイン.
        /// </summary>
        public static string _LOGIN_TITLE {
            get {
                return ResourceManager.GetString("_LOGIN_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ログアウト.
        /// </summary>
        public static string _LOGOUT_TITLE {
            get {
                return ResourceManager.GetString("_LOGOUT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ユーザー登録.
        /// </summary>
        public static string _REGISTER_TITLE {
            get {
                return ResourceManager.GetString("_REGISTER_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ユーザー情報をアップデート.
        /// </summary>
        public static string _UPDATE_TITLE {
            get {
                return ResourceManager.GetString("_UPDATE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 二要素認証が必要です。.
        /// </summary>
        public static string Account2FLoginRequired {
            get {
                return ResourceManager.GetString("Account2FLoginRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account is blocked.
        /// </summary>
        public static string AccountBlocked {
            get {
                return ResourceManager.GetString("AccountBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email not confirmed.
        /// </summary>
        public static string AccountEmailConfirmationRequired {
            get {
                return ResourceManager.GetString("AccountEmailConfirmationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation requires login.
        /// </summary>
        public static string AccountLoginRequired {
            get {
                return ResourceManager.GetString("AccountLoginRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation is not allowed for this user.
        /// </summary>
        public static string AccountNotAllowed {
            get {
                return ResourceManager.GetString("AccountNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ユーザーはすでに存在しました。.
        /// </summary>
        public static string AccountUserAlreadyExists {
            get {
                return ResourceManager.GetString("AccountUserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user and/or pasword.
        /// </summary>
        public static string AccountUserOrPasswordInvalid {
            get {
                return ResourceManager.GetString("AccountUserOrPasswordInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新しいパスワード確認.
        /// </summary>
        public static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パスワード確認.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to メールアドレス.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パスワードを忘れた方.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 接続を維持する.
        /// </summary>
        public static string IsPersistent {
            get {
                return ResourceManager.GetString("IsPersistent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ログイン.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ログアウト.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ログアウトして InfoHUB を離れようとしています。.
        /// </summary>
        public static string LogoutLine1 {
            get {
                return ResourceManager.GetString("LogoutLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ここをクリックして.
        /// </summary>
        public static string LogoutLine2_1 {
            get {
                return ResourceManager.GetString("LogoutLine2-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ログアウトします, または.
        /// </summary>
        public static string LogoutLine2_2 {
            get {
                return ResourceManager.GetString("LogoutLine2-2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ここをクリックして.
        /// </summary>
        public static string LogoutLine2_3 {
            get {
                return ResourceManager.GetString("LogoutLine2-3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 先のページへ戻る。.
        /// </summary>
        public static string LogoutLine2_4 {
            get {
                return ResourceManager.GetString("LogoutLine2-4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ログアウト.
        /// </summary>
        public static string LogoutPageTitle {
            get {
                return ResourceManager.GetString("LogoutPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新しいパスワード.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to レコードが見つかりません。.
        /// </summary>
        public static string NoRecordsFound {
            get {
                return ResourceManager.GetString("NoRecordsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ユーザーログイン未.
        /// </summary>
        public static string NoUserLogged {
            get {
                return ResourceManager.GetString("NoUserLogged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パスワード.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パスワードは正常に変更されました。.
        /// </summary>
        public static string PasswordChangeOk {
            get {
                return ResourceManager.GetString("PasswordChangeOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ユーザーを追加.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登録に成功！.
        /// </summary>
        public static string RegistrationOk {
            get {
                return ResourceManager.GetString("RegistrationOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to サーバーエラー。 後でもう一度やり直してください。.
        /// </summary>
        public static string ServerError {
            get {
                return ResourceManager.GetString("ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新成功しました。.
        /// </summary>
        public static string UpdateOk {
            get {
                return ResourceManager.GetString("UpdateOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ユーザーが見つかりません。.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ユーザーをアップデート.
        /// </summary>
        public static string UserUpdate {
            get {
                return ResourceManager.GetString("UserUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ようこそ!.
        /// </summary>
        public static string WelcomeLine1 {
            get {
                return ResourceManager.GetString("WelcomeLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InfoHUBにエントリーいただきありがとうございます。.
        /// </summary>
        public static string WelcomeLine2 {
            get {
                return ResourceManager.GetString("WelcomeLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to これから、社員ログイン ページに進んでください。.
        /// </summary>
        public static string WelcomeLine3 {
            get {
                return ResourceManager.GetString("WelcomeLine3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 現在ログインしている会社またはシャインはありません。.
        /// </summary>
        public static string WelcomeLine4 {
            get {
                return ResourceManager.GetString("WelcomeLine4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最初に企業プロファイルにログインしてから、従業員プロファイルにログインします。.
        /// </summary>
        public static string WelcomeLine5 {
            get {
                return ResourceManager.GetString("WelcomeLine5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 間違ったパスワード。.
        /// </summary>
        public static string WrongPassword {
            get {
                return ResourceManager.GetString("WrongPassword", resourceCulture);
            }
        }
    }
}
