//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JPLoto.Globalization.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LotoResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LotoResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JPLoto.Shared.Resources.LotoResource", typeof(LotoResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 項目正常に追加されました.
        /// </summary>
        public static string AddSuccess {
            get {
                return ResourceManager.GetString("AddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 項目はすでに存在します.
        /// </summary>
        public static string AlreadyExists {
            get {
                return ResourceManager.GetString("AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to フィルターを適用する.
        /// </summary>
        public static string ApplyFilters {
            get {
                return ResourceManager.GetString("ApplyFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提案適用.
        /// </summary>
        public static string ApplySuggestions {
            get {
                return ResourceManager.GetString("ApplySuggestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ボーナス数字.
        /// </summary>
        public static string Bonus {
            get {
                return ResourceManager.GetString("Bonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01 から 43 までの 1 つの数字をカンマで区切って入力してください.
        /// </summary>
        public static string BonusLoto6 {
            get {
                return ResourceManager.GetString("BonusLoto6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01 から 37 までの 2 つの数字をカンマで区切って入力してください.
        /// </summary>
        public static string BonusLoto7 {
            get {
                return ResourceManager.GetString("BonusLoto7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01 から 37 までの 1 つの数字をカンマで区切って入力してください.
        /// </summary>
        public static string BonusMiniLoto {
            get {
                return ResourceManager.GetString("BonusMiniLoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 編集をキャンセル.
        /// </summary>
        public static string CancelEditing {
            get {
                return ResourceManager.GetString("CancelEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 結果確認.
        /// </summary>
        public static string CheckResult {
            get {
                return ResourceManager.GetString("CheckResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to すべて削除.
        /// </summary>
        public static string ClearAll {
            get {
                return ResourceManager.GetString("ClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提案削除.
        /// </summary>
        public static string ClearSuggestions {
            get {
                return ResourceManager.GetString("ClearSuggestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 組み合わせ.
        /// </summary>
        public static string Combinations {
            get {
                return ResourceManager.GetString("Combinations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 印刷設定.
        /// </summary>
        public static string ConfigurePrinting {
            get {
                return ResourceManager.GetString("ConfigurePrinting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 項目削除.
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ボーナス番号は、抽選された数十とは異なる必要があります.
        /// </summary>
        public static string cr_BonusError {
            get {
                return ResourceManager.GetString("cr_BonusError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 等しい数字があります.
        /// </summary>
        public static string cr_DuplicateNumberError {
            get {
                return ResourceManager.GetString("cr_DuplicateNumberError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入力された情報が無効です.
        /// </summary>
        public static string cr_InputError {
            get {
                return ResourceManager.GetString("cr_InputError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ボーナス数字が無効です.
        /// </summary>
        public static string cr_InvalidBonusLenght {
            get {
                return ResourceManager.GetString("cr_InvalidBonusLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数字の数が無効です.
        /// </summary>
        public static string cr_InvalidNumbersLenght {
            get {
                return ResourceManager.GetString("cr_InvalidNumbersLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数字は入力されていません.
        /// </summary>
        public static string cr_MissingParametersError {
            get {
                return ResourceManager.GetString("cr_MissingParametersError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string cr_Ok {
            get {
                return ResourceManager.GetString("cr_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数値が範囲外です。 この宝くじの有効な数字を確認してください.
        /// </summary>
        public static string cr_OutOfRangeError {
            get {
                return ResourceManager.GetString("cr_OutOfRangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日にち.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 削除.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 完全に削除.
        /// </summary>
        public static string DeletePermanent {
            get {
                return ResourceManager.GetString("DeletePermanent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 項目正常に削除されました.
        /// </summary>
        public static string DeleteSuccess {
            get {
                return ResourceManager.GetString("DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 編集.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 回号.
        /// </summary>
        public static string Edition {
            get {
                return ResourceManager.GetString("Edition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 組み合わせ数が無効です.
        /// </summary>
        public static string Error_InvalidMaxCombinations {
            get {
                return ResourceManager.GetString("Error_InvalidMaxCombinations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 偶数.
        /// </summary>
        public static string EvenNumbers {
            get {
                return ResourceManager.GetString("EvenNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 組み合わせのフィルター.
        /// </summary>
        public static string FilterCombinations {
            get {
                return ResourceManager.GetString("FilterCombinations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to フィルター定義.
        /// </summary>
        public static string Filters {
            get {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to チェックすると、ランダムな組み合わせが生成されます.
        /// </summary>
        public static string GenerateRandom {
            get {
                return ResourceManager.GetString("GenerateRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 無効なボーナス.
        /// </summary>
        public static string InvalidBonus {
            get {
                return ResourceManager.GetString("InvalidBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 番号が無効です.
        /// </summary>
        public static string InvalidNumbers {
            get {
                return ResourceManager.GetString("InvalidNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to チェックを入れると以前の組み合わせが保持されます.
        /// </summary>
        public static string KeepPrevious {
            get {
                return ResourceManager.GetString("KeepPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 組み合わせを制限する.
        /// </summary>
        public static string LimitCombinations {
            get {
                return ResourceManager.GetString("LimitCombinations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数字の制限数.
        /// </summary>
        public static string LimitNumbers {
            get {
                return ResourceManager.GetString("LimitNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイルを開く.
        /// </summary>
        public static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ロト6.
        /// </summary>
        public static string Loto6 {
            get {
                return ResourceManager.GetString("Loto6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ロト７.
        /// </summary>
        public static string Loto7 {
            get {
                return ResourceManager.GetString("Loto7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max: .
        /// </summary>
        public static string Maximum {
            get {
                return ResourceManager.GetString("Maximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最大.
        /// </summary>
        public static string MaxValue {
            get {
                return ResourceManager.GetString("MaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mini Loto.
        /// </summary>
        public static string MiniLoto {
            get {
                return ResourceManager.GetString("MiniLoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最小.
        /// </summary>
        public static string MinValue {
            get {
                return ResourceManager.GetString("MinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 項目見つかりませんでした.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数字.
        /// </summary>
        public static string Numbers {
            get {
                return ResourceManager.GetString("Numbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 順番に数字.
        /// </summary>
        public static string NumbersInSequence {
            get {
                return ResourceManager.GetString("NumbersInSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to カンマで区切られた 01 から 43 までの 6 つの数字のリストを入力してください.
        /// </summary>
        public static string NumbersLoto6 {
            get {
                return ResourceManager.GetString("NumbersLoto6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to カンマで区切られた 01 から 37 までの 7 つの数字のリストを入力してください.
        /// </summary>
        public static string NumbersLoto7 {
            get {
                return ResourceManager.GetString("NumbersLoto7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to カンマで区切られた 01 から 31 までの 5 つの数字のリストを入力してください.
        /// </summary>
        public static string NumbersMiniLoto {
            get {
                return ResourceManager.GetString("NumbersMiniLoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 列ごとの数値.
        /// </summary>
        public static string NumbersPerColumn {
            get {
                return ResourceManager.GetString("NumbersPerColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 行あたりの数字.
        /// </summary>
        public static string NumbersPerLine {
            get {
                return ResourceManager.GetString("NumbersPerLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 奇数.
        /// </summary>
        public static string OddNumbers {
            get {
                return ResourceManager.GetString("OddNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作でエラーが発生しました.
        /// </summary>
        public static string OperationError {
            get {
                return ResourceManager.GetString("OperationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ＃順序.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ページ:.
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 一ページ目.
        /// </summary>
        public static string PageFirst {
            get {
                return ResourceManager.GetString("PageFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最後のページ.
        /// </summary>
        public static string PageLast {
            get {
                return ResourceManager.GetString("PageLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 次のページ.
        /// </summary>
        public static string PageNext {
            get {
                return ResourceManager.GetString("PageNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 前のページ.
        /// </summary>
        public static string PagePrevious {
            get {
                return ResourceManager.GetString("PagePrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 以前の組み合わせ.
        /// </summary>
        public static string PreviousCombinations {
            get {
                return ResourceManager.GetString("PreviousCombinations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 素数 .
        /// </summary>
        public static string PrimeNumbers {
            get {
                return ResourceManager.GetString("PrimeNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 印刷.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ランダムな組み合わせ.
        /// </summary>
        public static string RandomCombinations {
            get {
                return ResourceManager.GetString("RandomCombinations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to リサイクル.
        /// </summary>
        public static string Recycle {
            get {
                return ResourceManager.GetString("Recycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to リサイクルに移動.
        /// </summary>
        public static string RecycleItem {
            get {
                return ResourceManager.GetString("RecycleItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 戻す.
        /// </summary>
        public static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 項目戻す.
        /// </summary>
        public static string RestoreItem {
            get {
                return ResourceManager.GetString("RestoreItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 抽せん結果.
        /// </summary>
        public static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to フォルダーを選択.
        /// </summary>
        public static string SelectDiretory {
            get {
                return ResourceManager.GetString("SelectDiretory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提案.
        /// </summary>
        public static string Suggestions {
            get {
                return ResourceManager.GetString("Suggestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 組み合わせを生成する.
        /// </summary>
        public static string TITLE_COMBINATIONS {
            get {
                return ResourceManager.GetString("TITLE_COMBINATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 印刷設定.
        /// </summary>
        public static string TITLE_CONFIGURE_PRINTING {
            get {
                return ResourceManager.GetString("TITLE_CONFIGURE_PRINTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to フィルター設定.
        /// </summary>
        public static string TITLE_FILTERS {
            get {
                return ResourceManager.GetString("TITLE_FILTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ロト6.
        /// </summary>
        public static string TITLE_LOTO6 {
            get {
                return ResourceManager.GetString("TITLE_LOTO6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ロト７.
        /// </summary>
        public static string TITLE_LOTO7 {
            get {
                return ResourceManager.GetString("TITLE_LOTO7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mini Loto.
        /// </summary>
        public static string TITLE_MINILOTO {
            get {
                return ResourceManager.GetString("TITLE_MINILOTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 結果.
        /// </summary>
        public static string TITLE_RESULTS {
            get {
                return ResourceManager.GetString("TITLE_RESULTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数字を選択.
        /// </summary>
        public static string TITLE_SELECTNUMBERS {
            get {
                return ResourceManager.GetString("TITLE_SELECTNUMBERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 項目正常に変更されました.
        /// </summary>
        public static string UpdateSuccess {
            get {
                return ResourceManager.GetString("UpdateSuccess", resourceCulture);
            }
        }
    }
}
