//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JpLoto.Globalization.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PlanResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PlanResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JpLoto.Globalization.Resources.PlanResource", typeof(PlanResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 購読するに進む.
        /// </summary>
        public static string ClickHereToSubscribe {
            get {
                return ResourceManager.GetString("ClickHereToSubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 有効期限終了.
        /// </summary>
        public static string ExpiredIn {
            get {
                return ResourceManager.GetString("ExpiredIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 有効期限.
        /// </summary>
        public static string ExpiresIn {
            get {
                return ResourceManager.GetString("ExpiresIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 無料でお申し込み頂けます.
        /// </summary>
        public static string FreeTrial {
            get {
                return ResourceManager.GetString("FreeTrial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to フル機能を備えた 30 日間の無料トライアルにサインアップしてください。 クレジット カードは必要なく、この試用期間の終了時に料金が請求されることはありません。 幸運を！.
        /// </summary>
        public static string FreeTrialText {
            get {
                return ResourceManager.GetString("FreeTrialText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 申し訳ございませんが、利用不可.
        /// </summary>
        public static string NotAvailable {
            get {
                return ResourceManager.GetString("NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to サブスクリプションは 1 年月間有効です。 この期間の終了時に自動的に更新されることはありません。 その後、JpLoto を継続して使用するには、新たな定期購入を行ってください。.
        /// </summary>
        public static string OneYearSubscription {
            get {
                return ResourceManager.GetString("OneYearSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to サブスクリプションは 6 か月間有効です。 この期間の終了時に自動的に更新されることはありません。 その後、JpLoto を継続して使用するには、新たな定期購入を行ってください。.
        /// </summary>
        public static string SixMonthSubsciption {
            get {
                return ResourceManager.GetString("SixMonthSubsciption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 申し訳ございませんが、ごプランの有効期限が切れました.
        /// </summary>
        public static string SubscriptionExpired {
            get {
                return ResourceManager.GetString("SubscriptionExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 申し訳ありませんが、試用期間は終了しました.
        /// </summary>
        public static string TrialExpired {
            get {
                return ResourceManager.GetString("TrialExpired", resourceCulture);
            }
        }
    }
}
