//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JPLoto.Globalization.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PrintResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PrintResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JPLoto.Shared.Resources.PrintResource", typeof(PrintResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to カード高さ  (mm).
        /// </summary>
        public static string CardHeight {
            get {
                return ResourceManager.GetString("CardHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to カードのヘッダー余白  (mm).
        /// </summary>
        public static string CardMarginHeader {
            get {
                return ResourceManager.GetString("CardMarginHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to カードの左余白  (mm).
        /// </summary>
        public static string CardMarginLeft {
            get {
                return ResourceManager.GetString("CardMarginLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to カードの上余白  (mm).
        /// </summary>
        public static string CardMarginTop {
            get {
                return ResourceManager.GetString("CardMarginTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to カード印刷設定.
        /// </summary>
        public static string CardSettings {
            get {
                return ResourceManager.GetString("CardSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to カード幅  (mm).
        /// </summary>
        public static string CardWidth {
            get {
                return ResourceManager.GetString("CardWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用紙ヘッダー余白  (mm).
        /// </summary>
        public static string FormMarginHeader {
            get {
                return ResourceManager.GetString("FormMarginHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 紙の左余白  (mm).
        /// </summary>
        public static string FormMarginLeft {
            get {
                return ResourceManager.GetString("FormMarginLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用紙の上余白  (mm).
        /// </summary>
        public static string FormMarginTop {
            get {
                return ResourceManager.GetString("FormMarginTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用紙サイズ.
        /// </summary>
        public static string FormSize {
            get {
                return ResourceManager.GetString("FormSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用紙印刷設定.
        /// </summary>
        public static string PaperSettings {
            get {
                return ResourceManager.GetString("PaperSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 印刷設定.
        /// </summary>
        public static string TITLE_PRINTCONFIG {
            get {
                return ResourceManager.GetString("TITLE_PRINTCONFIG", resourceCulture);
            }
        }
    }
}
