//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JpLoto.Globalization.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MenuResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MenuResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JpLoto.Shared.Resources.MenuResource", typeof(MenuResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 組み合わせ生成.
        /// </summary>
        public static string Combinations {
            get {
                return ResourceManager.GetString("Combinations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to システム設定.
        /// </summary>
        public static string Configurations {
            get {
                return ResourceManager.GetString("Configurations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 組み合わせフィルター.
        /// </summary>
        public static string Filters {
            get {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ホム.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ログイン.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ログアウト.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ロト６.
        /// </summary>
        public static string Loto6 {
            get {
                return ResourceManager.GetString("Loto6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ロト7.
        /// </summary>
        public static string Loto7 {
            get {
                return ResourceManager.GetString("Loto7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ミニロト.
        /// </summary>
        public static string MiniLoto {
            get {
                return ResourceManager.GetString("MiniLoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 申込カード単価.
        /// </summary>
        public static string Pricing {
            get {
                return ResourceManager.GetString("Pricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 印刷設定.
        /// </summary>
        public static string PrintConfig {
            get {
                return ResourceManager.GetString("PrintConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to プライバシーポリシー.
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ユザー登録.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ロト６の抽選結果.
        /// </summary>
        public static string ResultsLoto6 {
            get {
                return ResourceManager.GetString("ResultsLoto6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ロト7の抽選結果.
        /// </summary>
        public static string ResultsLoto7 {
            get {
                return ResourceManager.GetString("ResultsLoto7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ミニロトの抽選結果.
        /// </summary>
        public static string ResultsMiniLoto {
            get {
                return ResourceManager.GetString("ResultsMiniLoto", resourceCulture);
            }
        }
    }
}
